# -*- coding: utf-8 -*-
{
    'name': 'SOLe KPI & Scorecard',
    'version': '19.0.2.0.0',
    'category': 'Productivity',
    'summary': 'Balanced Scorecard, KPI tracking, and Tender management for Softlink Options Limited',
    'author': 'SOLe',
    'website': 'https://softlinkoptions.co.ke',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'account', 'hr'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'data/kpi_categories.xml',
        'data/kpi_roles.xml',
        'data/kpi_indicators.xml',
        'data/kpi_periods.xml',
        'reports/kpi_scorecard_report.xml',
        'views/kpi_views.xml',
        'views/tender_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sole_kpi/static/src/css/sole_kpi.css',
            'sole_kpi/static/src/xml/kpi_dashboard.xml',
            'sole_kpi/static/src/js/kpi_dashboard.js',
            'sole_kpi/static/src/xml/kpi_company_scorecard.xml',
            'sole_kpi/static/src/js/kpi_company_scorecard.js',
            'sole_kpi/static/src/xml/kpi_entry_widget.xml',
            'sole_kpi/static/src/js/kpi_entry_widget.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
